name: Java CI with SonarQube (Self-Hosted)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start xvfb
        run: |
          export DISPLAY=:99
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Build with Maven
        run: mvn -B clean verify
        continue-on-error: true
        env:
          DISPLAY: :99
          
      - name: Test SonarQube connectivity
        run: curl -I ${{ secrets.SONAR_HOST_URL }}

      - name: Run SonarQube Scan
        run: mvn -B sonar:sonar \
          -Dsonar.projectKey=sonar-demo-java \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
